### ISSUE TITLE
Can not apply transform with ts-loader.

### ISSUE THREAD

**Issue by Alendorff** [rimeto/ts-optchain#43]
Hello there

I'm trying to use your transformer to get simple output instead of nested proxy-objects, but I struggle with that error now:

```
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'getTypeChecker' of undefined
    at visitNode (C:\Users\Foo\Desktop\vue-project\node_modules\ts-optchain\dist\transform\transform.js:22:31)
    at visitNodeAndChildren (C:\Users\Foo\Desktop\vue-project\node_modules\ts-optchain\dist\transform\transform
.js:19:30)
    at C:\Users\Foo\Desktop\vue-project\node_modules\ts-optchain\dist\transform\transform.js:15:65
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1390:86
    at reduceLeft (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1102:30)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1390:42
    at transformRoot (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81154:82)
    at Object.map (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:429:29)
    at Object.transformNodes (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81141:
30)
    at emitJsFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81497:32)
    at emitSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81465
:13)
    at forEachEmittedFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81373:30)
    at Object.emitFiles (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81454:9)
    at emitWorker (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:86927:33)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:86887:66
    at runWithCancellationToken (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:869
79:24)
```

I tried to integrate your transform fn into my webpack config which I used to build vue based project, so I just wanted to utilize that [getCustomTransformers option](https://github.com/TypeStrong/ts-loader#getcustomtransformers--program-program---before-transformerfactory-after-transformerfactory--) so after the edits config looks like that:

```js
    rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
        options: {
          transpileOnly: true,
          getCustomTransformers: (program) => ({
              after: [optChainTransform(program)]
          }),
          appendTsSuffixTo: [/\.vue$/]
        }
      }
      /*...*/
    ],
    plugins: [new VueLoaderPlugin(), new ForkTsCheckerWebpackPlugin()],
```

I use common typescript compiler, because I couldn't make it done with ttsc - output bundle still have not-replaced `oc()` calls so it's still just recursive-proxy objects which I want to avoid. I thought maybe the problem in `transpileOnly` but I can't refuse from it, project builds too long without it - so I started to search a way how to utilize this transform thing with my current config and I believed the code I provided above should work, but it doesn't. So I just wanted to ask maybe you have some ideas why, because I have no idea at the moment. 

Thanks in advance.

**Comment by Alendorff** [comment]
Changing options to 
```js
getCustomTransformers: () => ({
              after: [optChainTransform]
          }),
```
gives another error:
```
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'kind' of undefined
    at Object.isSourceFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:13697:21
)
    at emitShebangIfNeeded (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:83984:20
)
    at Object.writeFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81838:13)
    at printSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:8160
2:25)
    at emitJsFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81518:13)
    at emitSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81465
:13)
    at forEachEmittedFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81373:30)
    at Object.emitFiles (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81454:9)
    at emitWorker (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:86927:33)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:86887:66
    at runWithCancellationToken (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:869
79:24)
    at Object.emit (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:86887:20)
    at Object.transpileModule (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:10517
2:17)
    at getTranspilationEmit (C:\Users\Foo\Desktop\vue-project\node_modules\ts-loader\dist\index.js:231:74)
    at successLoader (C:\Users\Foo\Desktop\vue-project\node_modules\ts-loader\dist\index.js:33:11)
    at Object.loader (C:\Users\Foo\Desktop\vue-project\node_modules\ts-loader\dist\index.js:21:12)
```

**Comment by Alendorff** [comment]
Changing import to as described here:
```
getCustomTransformers: resolve('build/webpack.ts-transformers.js')
```
Gives another error
```
\typescript.js:63475:36)
    at visitSourceFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:66199:53)
    at saveStateAndInvoke (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:65832:27
)
    at transformSourceFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:65815:2
7)
    at transformSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js
:65795:20)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1390:86
    at reduceLeft (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1102:30)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1390:42
    at transformRoot (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81154:82)
    at Object.map (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:429:29)
    at Object.transformNodes (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81141
:30)
    at emitJsFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81497:32
)
    at emitSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:8146
5:13)
    at forEachEmittedFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81373:30
)
```

**Comment by Alendorff** [comment]
Changing `after` to `before` gives yet another error:

```
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'length' of undefined
    at Object.firstOrUndefined (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:998
:22)
    at Object.startsWithUseStrict (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:
62523:33)
    at Object.visitLexicalEnvironment (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript
.js:63475:36)
    at visitSourceFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:66199:53)
    at saveStateAndInvoke (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:65832:27
)
    at transformSourceFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:65815:2
7)
    at transformSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js
:65795:20)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1390:86
    at reduceLeft (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1102:30)
    at C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:1390:42
    at transformRoot (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81154:82)
    at Object.map (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:429:29)
    at Object.transformNodes (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81141
:30)
    at emitJsFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81497:32
)
    at emitSourceFileOrBundle (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:8146
5:13)
    at forEachEmittedFile (C:\Users\Foo\Desktop\vue-project\node_modules\typescript\lib\typescript.js:81373:30
)
```
